Controllers/BrandController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using InventoryBeginners.Data;
using InventoryBeginners.Models;
using System.Collections.Generic;
using System;
using System.Linq;
using InventoryBeginners.Interfaces;
using CodesByAniz.Tools;
using Microsoft.AspNetCore.Authorization;

namespace InventoryBeginners.Controllers
{
    
    public class BrandController : Controller
    {

        private readonly IBrand _Repo;
        public BrandController(IBrand repo) // here the repository will be passed by the dependency injection.
        {
            _Repo = repo;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Index(string sortExpression = "", string SearchText = "", int pg = 1, int pageSize = 5)
        {
            SortModel sortModel = new SortModel();
            sortModel.AddColumn("name");
            sortModel.AddColumn("description");
            sortModel.ApplySort(sortExpression);
            ViewData["sortModel"] = sortModel;

            ViewBag.SearchText = SearchText;

            PaginatedList<Brand> items = _Repo.GetItems(sortModel.SortedProperty, sortModel.SortedOrder, SearchText, pg, pageSize);


            var pager = new PagerModel(items.TotalRecords, pg, pageSize);
            pager.SortExpression = sortExpression;
            this.ViewBag.Pager = pager;


            TempData["CurrentPage"] = pg;


            return View(items);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            Brand item = new Brand();
            return View(item);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Create(Brand item)
        {
            bool bolret = false;
            string errMessage = "";
            try
            {
                if (item.Description.Length < 4 || item.Description == null)
                    errMessage = "Description Must be atleast 4 Characters";

                if (_Repo.IsItemExists(item.Name) == true)
                    errMessage = errMessage + " " + " Name " + item.Name + " Exists Already";

                if (errMessage == "")
                {
                    item = _Repo.Create(item);
                    bolret = true;
                }
            }
            catch (Exception ex)
            {
                errMessage = errMessage + " " + ex.Message;
            }
            if (bolret == false)
            {
                TempData["ErrorMessage"] = errMessage;
                ModelState.AddModelError("", errMessage);
                return View(item);
            }
            else
            {
                TempData["SuccessMessage"] = "" + item.Name + " Created Successfully";
                return RedirectToAction(nameof(Index));
            }
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Details(int id) //Read
        {
            Brand item = _Repo.GetItem(id);
            return View(item);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id)
        {
            Brand item = _Repo.GetItem(id);
            TempData.Keep();
            return View(item);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Edit(Brand item)
        {
            bool bolret = false;
            string errMessage = "";

            try
            {
                if (item.Description.Length < 4 || item.Description == null)
                    errMessage = "Description Must be atleast 4 Characters";

                if (_Repo.IsItemExists(item.Name, item.Id) == true)
                    errMessage = errMessage + item.Name + " Already Exists";

                if (errMessage == "")
                {
                    item = _Repo.Edit(item);
                    TempData["SuccessMessage"] = item.Name + ", Saved Successfully";
                    bolret = true;
                }
            }
            catch (Exception ex)
            {
                errMessage = errMessage + " " + ex.Message;
            }



            int currentPage = 1;
            if (TempData["CurrentPage"] != null)
                currentPage = (int)TempData["CurrentPage"];


            if (bolret == false)
            {
                TempData["ErrorMessage"] = errMessage;
                ModelState.AddModelError("", errMessage);
                return View(item);
            }
            else
                return RedirectToAction(nameof(Index), new { pg = currentPage });
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            Brand item = _Repo.GetItem(id);
            TempData.Keep();
            return View(item);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Delete(Brand item)
        {
            try
            {
                item = _Repo.Delete(item);
            }
            catch (Exception ex)
            {
                string errMessage = ex.Message;
                TempData["ErrorMessage"] = errMessage;
                ModelState.AddModelError("", errMessage);
                return View(item);

            }

            int currentPage = 1;
            if (TempData["CurrentPage"] != null)
                currentPage = (int)TempData["CurrentPage"];

            TempData["SuccessMessage"] = item.Name + " Deleted Successfully";
            return RedirectToAction(nameof(Index), new { pg = currentPage });


        }


    }
}

Controllers/OrderController.cs
using InventoryBeginners.Interfaces;
using InventoryBeginners.Models;
using Microsoft.AspNetCore.Mvc;

namespace InventoryBeginners.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrder _OrderService;
        private readonly IShoppingCart _ShoppingCartService;

        public OrderController(IOrder OrderService, IShoppingCart ShoppingCartService)
        {
            _OrderService = OrderService;
            _ShoppingCartService = ShoppingCartService;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Order(ShoppingCart cart,string userId)
        {
            _OrderService.order(cart, userId);
            var orders = _OrderService.GetOrdersByUser(userId);
            _ShoppingCartService.RemoveItem("-1");
            return View("Index", orders);
        }
        public IActionResult OrderList()
        {
            // Récupérer toutes les commandes à partir du service
            var orders = _OrderService.GetAllOrders();

            // Passez les commandes à la vue
            return View(orders);
        }
        public IActionResult OrdersByUser(string userId)
        {
            // Récupérer les commandes pour un utilisateur spécifique
            var orders = _OrderService.GetOrdersByUser(userId);

            // Passez les commandes à la vue
            return View("Index", orders);
        }


    }
}

Controllers/UnitController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using InventoryBeginners.Data;
using InventoryBeginners.Models;
using System.Collections.Generic;
using System;
using System.Linq;
using InventoryBeginners.Interfaces;
using CodesByAniz.Tools;
using Microsoft.AspNetCore.Authorization;

namespace InventoryBeginners.Controllers
{
    
    public class UnitController : Controller
    {       
        
        private readonly IUnit _unitRepo;
        public UnitController(IUnit unitrepo) // here the repository will be passed by the dependency injection.
        {            
            _unitRepo = unitrepo;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Index(string sortExpression="", string SearchText = "",int pg=1,int pageSize=5) 
        {
            SortModel sortModel = new SortModel();
            sortModel.AddColumn("name");
            sortModel.AddColumn("description");
            sortModel.ApplySort(sortExpression);
            ViewData["sortModel"] = sortModel;
            
            ViewBag.SearchText = SearchText;

            PaginatedList<Unit> units = _unitRepo.GetItems(sortModel.SortedProperty, sortModel.SortedOrder,SearchText,pg,pageSize);            
            

            var pager = new PagerModel(units.TotalRecords, pg, pageSize);
            pager.SortExpression = sortExpression;
            this.ViewBag.Pager = pager;


            TempData["CurrentPage"] = pg;


            return View(units);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            Unit unit = new Unit();
            return View(unit);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]  
        public IActionResult Create(Unit unit)
        {
            bool bolret = false;
            string errMessage = "";
            try
            {
                if (unit.Description.Length < 4 || unit.Description == null)               
                    errMessage = "Unit Description Must be atleast 4 Characters";

                if (_unitRepo.IsUnitNameExists(unit.Name) == true)
                    errMessage = errMessage + " " + " Unit Name " + unit.Name +" Exists Already";

                if (errMessage == "")
                {
                    unit = _unitRepo.Create(unit);
                    bolret = true;
                }                
            }
            catch(Exception ex) 
            {
                errMessage = errMessage + " " + ex.Message;
            }
            if (bolret == false)
            {
                TempData["ErrorMessage"] = errMessage;
                ModelState.AddModelError("", errMessage);
                return View(unit);
            }
            else
            {
                TempData["SuccessMessage"] = "Unit " + unit.Name + " Created Successfully";
                return RedirectToAction(nameof(Index));
            }
        }

        public IActionResult Details(int id) //Read
        {
            Unit unit =_unitRepo.GetUnit(id);              
            return View(unit);        
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id)
        {
            Unit unit = _unitRepo.GetUnit(id);
            TempData.Keep();
            return View(unit);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Edit(Unit unit)
        {
            bool bolret = false;
            string errMessage = "";

            try
            {
                if (unit.Description.Length < 4 || unit.Description == null)                
                   errMessage = "Unit Description Must be atleast 4 Characters";

                if (_unitRepo.IsUnitNameExists(unit.Name, unit.Id) == true)
                    errMessage = errMessage + "Unit Name " + unit.Name + " Already Exists";

                if (errMessage == "")
                {
                    unit = _unitRepo.Edit(unit);
                    TempData["SuccessMessage"] = unit.Name + ", Unit Saved Successfully";
                    bolret = true;
                }
            }
            catch(Exception ex)
            {
                errMessage = errMessage + " " + ex.Message;                
            }

          

            int currentPage = 1;
            if (TempData["CurrentPage"] != null)
                currentPage = (int)TempData["CurrentPage"];

          
            if(bolret==false)
            {
                TempData["ErrorMessage"] = errMessage;
                ModelState.AddModelError("", errMessage);
                return View(unit);
            }
            else
            return RedirectToAction(nameof(Index),new {pg=currentPage});
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            Unit unit = _unitRepo.GetUnit(id);
            TempData.Keep();
            return View(unit);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Delete(Unit unit)
        {
            try
            {
                unit = _unitRepo.Delete(unit);
            }
            catch(Exception ex)
            {
                string errMessage = ex.Message;
                TempData["ErrorMessage"] = errMessage;
                ModelState.AddModelError("", errMessage);
                return View(unit);
            }          
            
            int currentPage = 1;
            if (TempData["CurrentPage"] != null)
                currentPage = (int)TempData["CurrentPage"];

            TempData["SuccessMessage"] = "Unit " + unit.Name + " Deleted Successfully";
            return RedirectToAction(nameof(Index), new { pg = currentPage });


        }

     
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using InventoryBeginners.Models

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>E-commerce</title>
    <!-- Custom fonts for this template-->
    <link href="~/Theme/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/Theme/css/sb-admin-2.min.css" rel="stylesheet">
</head>
@{
    string menuTextColor = "text-white";

}
<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <!-- Sidebar - Brand -->
            @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
            {
                <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/Identity/Account/Manage">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Admin</div>
            </a>
            }
            @if (SignInManager.IsSignedIn(User) && User.IsInRole("User"))
            {
                if (User.Identity.IsAuthenticated)
                {
                    // Utilize HttpContext.RequestServices to access the IServiceProvider
                    var userManager = Context.RequestServices.GetService(typeof(UserManager<IdentityUser>)) as UserManager<IdentityUser>;

                    // Ensure that user is correctly typed as IdentityUser and use await with GetUserAsync
                    var user = await userManager.GetUserAsync(User);

                    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/Identity/Account/Manage">
                        <div class="sidebar-brand-icon rotate-n-15">
                        <i class="fas fa-laugh-wink"></i>
                        </div>
                        <div class="sidebar-brand-text mx-3">@user?.UserName</div>
                    </a>
                }
            }

            <!-- Divider -->
            <hr class="sidebar-divider my-0">
            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" asp-action="Index" asp-controller="Home">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
                        <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5z" />
                    </svg>
                    <span>Home</span>
                </a>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider">
           
    
            <!-- Nav Item - Pages Collapse Menu -->
            @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
            { 
                <li class="nav-item">
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                       aria-expanded="true" aria-controls="collapseTwo">
                        <i class="fas fa-fw fa-cog"></i>
                        <span>Menu</span>
                    </a>
                    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                        <div class="py-2 collapse-inner rounded" style="background-color:#4e73df">
                            <a class="nav-link text-white" asp-area="" asp-controller="Unit" asp-action="Index">Unit</a>
                            <a class="nav-link text-white" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                            <a class="nav-link text-white" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                            <a class="nav-link text-white" asp-area="" asp-controller="Brand" asp-action="Index">Brands</a>
                            <a class="nav-link text-white" asp-area="" asp-controller="ProductProfile" asp-action="Index">Consumers</a>
                            <a class="nav-link text-white" asp-area="" asp-controller="ProductGroup" asp-action="Index">Subcategories</a>
                            <a class="nav-link @menuTextColor" asp-area="" asp-controller="Supplier" asp-action="Index">Suppliers</a>
                        </div>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Order" asp-action="OrderList">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-card-list" viewBox="0 0 16 16">
                            <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2z" />
                            <path d="M5 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 5 8m0-2.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5m0 5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5m-1-5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0M4 8a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0m0 2.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0" />
                        </svg>
                        Order List
                    </a>
                </li>

            }
            @if (SignInManager.IsSignedIn(User) && User.IsInRole("User"))
            {
                string userId = "";

                if (User.Identity.IsAuthenticated)
                {
                    // Utilize HttpContext.RequestServices to access the IServiceProvider
                    var userManager = Context.RequestServices.GetService(typeof(UserManager<IdentityUser>)) as UserManager<IdentityUser>;

                    // Ensure that user is correctly typed as IdentityUser and use await with GetUserAsync
                    var user = await userManager.GetUserAsync(User);

                    // Exemple : Obtenez l'ID de l'utilisateur
                    userId = user?.Id;

                    
                        string x = userId;
                    
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="ShoppingCart" asp-action="Index">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                            <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5M3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4m7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4m-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2m7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2" />
                        </svg>
                        View Cart
                        
                    </a>
                    </li>
                    <li class="nav-item">
                      
                        <form asp-controller="Order" asp-action="OrdersByUser" method="post">
                            <input type="hidden" name="UserId" value="@user?.Id" />
                            <button type="submit" class="nav-link text-white" style="background-color:#4e73df; border:hidden" >
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list-ul" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M5 11.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5m-3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2m0 4a1 1 0 1 0 0-2 1 1 0 0 0 0 2m0 4a1 1 0 1 0 0-2 1 1 0 0 0 0 2" />
                                </svg>
                                Order List
                            </button>
                        </form>
                    </li>
                }
            }



            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                <nav class="navbar navbar-expand  bg-white topbar mb-4 static-top shadow">
                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>
                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto" >
                        <partial name="_LoginPartial" />
                    </ul>
                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!-- Content Row -->
               
                    <div class="row">
                        <div class="container body-content">
                            @RenderBody()
                          
                        </div>
                        @RenderSection("scripts", required: false)
                    </div>
                </div>
            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; E-commerce 2024 </span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->
        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/Theme/vendor/jquery/jquery.min.js"></script>
    <script src="~/Theme/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Theme/js/sb-admin-2.min.js"></script>



</body>
</html>

Views/Shared/_bottomBar.cshtml
@model PagerModel

<div class="container m-0 p-0 btn-group" style="background-color:#4e73df; border-radius:10px;  height:45px; color:white;">

    <div class="col-4 btn-group p-1 m-1">
        <p>
            Showing @Model.StartRecord to @Model.EndRecord of @Model.TotalItems Rows
        </p>
    </div>



    <div class="col-3 btn-group justify-content-end">
        <span class="col-7 mt-2 p-0">
            Rows Per Page
        </span>

        <span class="col-5 p-1">
            <select class="form-control" id="pageSelector" asp-items="Model.GetPageSizes();"
                    onchange="ChangePageSize(this);">
            </select>
        </span>
    </div>



    <div class="col-4 btn-group justify-content-end mt-2">
        <p>
            Showing @Model.CurrentPage / @Model.TotalPages Pages
        </p>
    </div>


</div>

<script>
    function ChangePageSize(obj)
    {
        var controllerName = '@this.ViewContext.RouteData.Values["controller"].ToString()';
        window.location.href = "/" + controllerName + "/@Model.Action" + "?pageSize=" + obj.value + "&SearchText@Model.SearchText" + "&sortExpression=" + "@Model.SortExpression";
    }

</script>

Views/Shared/_topBar.cshtml
@model PagerModel


<style>
    .page-link {
        color: black !important;
    }

    .page-item.active .page-link {
        z-index: 3;
        color: #fff;
        background-color: #DFBA4E !important;
        border-color: #DFBA4E;
    }
</style>

<div class="container btn-group" style="background-color:#4e73df; border-radius:10px; height:45px;">

    <div class="col-4 p-0 justify-content-end mt-1">
        <form asp-action="index">
            <span class="btn-group">
                <input class="form-control" type="text"
                       name="SearchText"
                       value="@ViewBag.SearchText"
                       placeholder="Search Key" />

                <span class="ml-2 btn-group " style="border-radius:10px;background-color:#DFBA4E ">
                    <i class="pl-2 fa fa-search align-self-center" aria-hidden="true"></i>
                    <input class="btn btn-sm font-weight-bold text-black"
                           type="submit" value="Search" />
                </span>



            </span>
        </form>
    </div>

    <div class="container mt-1">

        <ul class="pagination justify-content-end">

            @if (Model.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-action="@Model.Action"
                       asp-route-pg="1"
                       asp-route-pageSize="@Model.PageSize"
                       asp-route-SearchText="@Model.SearchText"
                       asp-route-sortExpression="@Model.SortExpression">
                        First
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-action="@Model.Action"
                       asp-route-pg="@(Model.CurrentPage-1)"
                       asp-route-pageSize="@Model.PageSize"
                       asp-route-SearchText="@Model.SearchText"
                       asp-route-sortExpression="@Model.SortExpression">
                        Previous
                    </a>
                </li>
            }



            @for (var pge = Model.StartPage; pge <= Model.EndPage; pge++)
            {
                <li class="page-item @(pge==Model.CurrentPage ?"active" : "")">
                    @if (pge != Model.CurrentPage)
                    {
                        <a class="page-link" asp-action="@Model.Action"
                           asp-route-pg="@pge"
                           asp-route-pageSize="@Model.PageSize"
                           asp-route-SearchText="@Model.SearchText"
                           asp-route-sortExpression="@Model.SortExpression">
                            @pge
                        </a>
                    }
                    else
                    {
                        <span class="page-link">@pge</span>
                    }
                </li>

            }



            @if (Model.CurrentPage < Model.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" asp-action="@Model.Action"
                       asp-route-pg="@(Model.CurrentPage+1)"
                       asp-route-pageSize="@Model.PageSize"
                       asp-route-SearchText="@Model.SearchText"
                       asp-route-sortExpression="@Model.SortExpression">
                        Next
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-action="@Model.Action"
                       asp-route-pg="@(Model.TotalPages)"
                       asp-route-pageSize="@Model.PageSize"
                       asp-route-SearchText="@Model.SearchText"
                       asp-route-sortExpression="@Model.SortExpression">
                        Last
                    </a>
                </li>
            }




        </ul>
    </div>

</div>